version: 2
updates:
  # Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all development dependencies together
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    # Ignore low-severity alerts for development dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        severity: "low"

  # Monitor npm dependencies (if you add package.json in the future)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-development-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        severity: "low"

  # Monitor Docker dependencies (if you add Docker in the future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        severity: "low"
